var WHITERUN = 0;
var MEET_CHICKEN = 1;
var KILL_CHICKEN = 2;
var KILLED_BY_VILLAGERS = 3;
var DRAGONSREACH = 4; // The palace in Whiterun
var MEET_LYDIA = 5;
var WITH_LYDIA = 6;
var REJECT_LYDIA = 7;
var GOLDEN_CLAW = 8;
var RESCUED = 9;
var WINTERHOLD = 10; // School of the arcane arts
var DRAGON_SHOUT = 11;
var FALL_IN_LOVE = 12;
var ELDERRLY_MAGE = 13;
var BE_HERO = 14;
var KILLED_BY_DRAGON = 15;

var STR_0 = 'Dragonborn walks to Whiterun, a major city located in the center of Skyrim.'
var STR_1 = 'When he is walking in the street, there is a chick looking at him.'
var STR_2 = 'Dragonborn takes out his sword and kills the poor chick.'
var STR_3 = 'What?! All villagers come out with their weapons on. Dragonborn is then catched and sent to prison.'
var STR_4 = 'What a lovely chick. But he doesn\'t wate time on it and heads to the Dragonsreach.'
var STR_5 = 'The jarl lets Lydia to be my housecarl. "I will be your shield and sword." The girl says.'
var STR_6 = '"Okay, Come with me." Dragonborn says."Let\'s battle together!"'
var STR_7 = '"I don\'t need a girl to help me, I can handle everything." Dragonborn says.'
var STR_8 = 'Then Farengar, the court wizard, wants me to fetch the Golden Claw.'
var STR_9 = '"No problem!" Then Dragonborn goes to Dragonstone to find the Golden Claw. In the battle, Lydia saves his life.'
var STR_10 = '"Sorry, but I don\'t want to do this for you." Dragonborn went to Winterhold to learn magic.'
var STR_11 = '"No problem!" Then Dragonborn goes to Dragonstone to find the Golden Claw. In there, he leanrs how to mmake dragon shouts.'
var STR_12 = 'After many adventures, Dragonborn and Lydia finally fall in love with each other. They live a happy life after wedding.'
var STR_13 = 'Lydia isn\'t a fan of magic, so Dragonborn studies in Winterhold lonely. Finally, he becomes the Elderly Mage.'
var STR_14 = 'Dragonborn finally becomes a hero because of his effort in the war against dragons.'
var STR_15 = 'Dragonborn has to enter the war against dragons. Unfortunately he was killed by Alduin, an immensely powerful dragon.'
